name: Feature Request
description: Suggest a new feature for tan-pagination
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions you've considered
      placeholder: "Alternative approaches could be..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: "In my application, I need to..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Code Example
      description: Show how you would like to use this feature
      render: javascript
      placeholder: |
        // Example of how the feature would be used
        import { pagination } from 'tan-pagination';
        
        const result = pagination.someNewFeature(data, options);

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility
      description: Should this feature maintain backward compatibility?
      options:
        - label: This feature should be backward compatible
          required: false
        - label: This feature may require breaking changes
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information... 